version: 0.2

env:
  variables:
    key: "S3_BUCKET"
    key: "TESTRAIL_DOMAIN"
    key: "TESTRAIL_USERNAME"
    key: "TESTRAIL_APIKEY"
    key: "TESTRAIL_PROJECTID"
    key: "TESTRAIL_RUNID"
    key: "TESTRAIL_TITLE"
    

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - npm install -g newman-reporter-testrail
      - yum install -y jq

  pre_build:
    commands:
      - cd ./02postman
      - ./update-postman-env-file.sh

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - ./run_newman.sh
      - newman run SignosoftAPITests.postman_collection.json --environment TEST.postman_environment.json -r junit

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: '02postman/newman' # Location of the reports
